prefix dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix : <http://wot.barneyb.com/wot/>
SELECT ?p ?o ?ann ?v
WHERE { {   { ?s ?p ?o }
            union
            {   [    a owl:Axiom ;
                     owl:annotatedSource ?s ;
                     owl:annotatedProperty ?p ;
                     owl:annotatedTarget ?o ;
                     ?ann ?v ;
                ] .
                filter ( ?ann != rdf:type )
            }
        }
        filter ( ?s = :RandAlThor )
      }
order by ?p ?o
